language: php
sudo: false
matrix:
  fast_finish: true
cache:
- vendor
- bin
php:
- 5.5
- 5.6
- 7.0
before_script:
- composer install
- mkdir -p build/logs
script:
- make lint
- make test
after_script:
- bin/coveralls -v
